<a href="https://colab.research.google.com/github/zekeowen/Scratch/blob/main/Data_Science_Lifecycle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## How to use Colaboratory notebook

This notebook includes an example of using `numpy` library to create a $3\times4$ matrix filled with random numbers between 1 and 10.

In [ ]:
import numpy as np

# Create an array of random numbers
random_nums = np.random.randint(low=1, high=10, size=(3, 4))
print("Random Numbers:")
print(random_nums)

Random Numbers:
[[6 3 7 4]
 [1 5 4 7]
 [9 4 1 1]]


In [1]:
# Calculate the sum, minimum, and maximum of the array
print("\nSum:", np.sum(random_nums))
print("Minimum:", np.min(random_nums))
print("Maximum:", np.max(random_nums))

NameError: name 'np' is not defined